AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 420

Resources:
  MyQManagerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /devices
            Method: GET
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  MyQManagerAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/devices/"
  MyQManagerFunction:
    Description: "My Q Manager Function ARN"
    Value: !GetAtt MyQManagerFunction.Arn
  MyQManagerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MyQManagerFunctionRole.Arn
